# Generated by Django 5.1.1 on 2024-11-02 03:50

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventariosTec', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordentrabajo',
            name='fecha',
        ),
        migrations.AddField(
            model_name='ordentrabajo',
            name='fecha_fin',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ordentrabajo',
            name='fecha_inicio',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='prestamo',
            name='activo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='prestamodetalle',
            name='estado',
            field=models.CharField(choices=[('prestado', 'Prestado'), ('regresado', 'Regresado'), ('consumido', 'Consumido')], default='prestado', max_length=10),
        ),
        migrations.AddField(
            model_name='producto',
            name='estado',
            field=models.CharField(choices=[('bueno', 'Bueno'), ('malo', 'Malo'), ('regular', 'Regular'), ('sin_estado', 'Sin Estado')], default='sin_estado', max_length=10),
        ),
    ]
