# Generated by Django 5.1.1 on 2024-11-02 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventariosTec', '0002_remove_ordentrabajo_fecha_ordentrabajo_fecha_fin_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordentrabajo',
            name='estado',
            field=models.CharField(choices=[('sin_asignar', 'Sin Asignar'), ('en_proceso', 'En Proceso'), ('finalizado', 'Finalizado'), ('truncada', 'Truncada')], default='sin_asignar', max_length=12),
        ),
    ]
