# Generated by Django 5.1.1 on 2024-11-03 10:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventariosTec', '0005_ordentrabajo_asignado_a_ordentrabajo_creador'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prestamo_Detalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_prestada', models.DecimalField(decimal_places=2, max_digits=10)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventariosTec.producto')),
            ],
        ),
    ]
