# Generated by Django 5.1.1 on 2024-11-04 02:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventariosTec', '0006_prestamo_detalle'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Prestamo_Detalle',
        ),
    ]
